# System Prompt Generator 設定ファイル

# アプリケーション設定
[app]
header = "This is Header!"

[tools.claude]
generate = true # false だと生成されない。デフォルトは true
dir_name = ""   # 未指定の場合はデフォルトの位置に配置される
file_name = ""  # 未指定の場合は CLAUDE.md になる

[tools.cline]
generate = true

# カスタム設定例
[tools.cursor]
generate = true
dir_name = "config"
file_name = "cursor_rules.md"

[tools.aider]
generate = true
dir_name = ""
file_name = ".aider_prompt"
