# System Prompt Generator 設定ファイル

# アプリケーション設定
[app]
language = ""       # 言語設定: "ja" (日本語), "en" (英語), "" (自動検出)

[claude]
generate = true      # false だと生成されない。デフォルトは true
path = ""           # 未指定の場合はデフォルトの位置に配置される
file_name = ""      # 未指定の場合は CLAUDE.md になる

[cline]
generate = true
path = ""
file_name = ""      # 未指定の場合は .clinerules になる

# カスタム設定例
[custom.cursor]
generate = true
path = "./config"
file_name = "cursor_rules.md"

[custom.aider]
generate = true
path = "./"
file_name = ".aider_prompt"